SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS HIGHSCORES;

USE HIGHSCORES;

SHOW TABLES;


CREATE TABLE IF NOT EXISTS HIGHSCORES (  
    id INT AUTO_INCREMENT PRIMARY KEY,
    playername VARCHAR(255), 
    score DECIMAL(7,2),
    playtime DATETIME DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE HIGHSCORES;

INSERT INTO HIGHSCORES (playername, score) VALUES ("Olli K", 50);  
INSERT INTO HIGHSCORES (playername, score) VALUES ("Henkka K", 150); 
INSERT INTO HIGHSCORES (playername, score) VALUES ("Ismo J", 70);  
INSERT INTO HIGHSCORES (playername, score) VALUES ("Matti W", 90); 

INSERT INTO HIGHSCORES (playername, score) VALUES ("Hessu", 95); 

SELECT * FROM HIGHSCORES ORDER BY score DESC LIMIT 3;

SELECT * FROM HIGHSCORES WHERE playername = "Hessu";